# Generated by Django 5.0 on 2025-03-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
