# Generated by Django 5.0 on 2025-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_transaction_amount_alter_wallet_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=42)),
                ('recipient', models.CharField(max_length=42)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('tx_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
